### ISSUE TITLE
Android/Browser: Cancelling sign-in on beer site does not refresh Sign In

### ISSUE THREAD

**Issue by shane-tomlinson** [lloyd/myfavoritebeer.org#32] opened 2011-11-03 11:40 UTC
Originally reported by @jbonacci at https://github.com/mozilla/browserid/issues/492

Found this while testing Android compatibility (old firmware).

Using the stock browser (Browser)
Bring up beta.myfavoritebeer.org
Click on Sign In
This should open a "pop up" window with the Email field.
Click the X button in the upper right corner to cancel and close this pop-up.
Note that clicking on the Sign In button again does not open the pop-up
The beer site must be refreshed in order to make the button active again.

**Comment by ghost** [comment] 2011-11-07 13:16
@shane-tomlinson - this issue is a duplicate of https://github.com/lloyd/myfavoritebeer.org/issues/26.

**Comment by benadida** [comment] 2011-11-29 19:10
this is almost certainly an issue with our library, so closing this and referencing:

https://github.com/mozilla/browserid/issues/492

ahah, I cannot close, @lloyd can you close?

**Comment by lloyd** [comment] 2011-11-29 20:52
with pleasure.

**Closed as completed by lloyd** 2011-11-29 20:52 UTC
